// LeetCode Solution for design-movie-rental-system
// Generated by LeetCode Mentor

class MovieRentingSystem {
public:

    map<pair<int,int>,int>getPrice;
    map<int, set<pair<int,int>>>movieDetails;
    set<tuple<int,int,int>>rented; //price,shop,movie
    MovieRentingSystem(int n, vector<vector<int>>& entries) {
        // we need two maps one to get the price corresponding to a mmovie and shop
        // one to get the movie corresponding to a shop and price
        for(auto it:entries){
            getPrice[{it[0],it[1]}] = it[2]; //shop,movie --> price

