const vscode = require('vscode');

function activate(context) {
  console.log('Activating LeetCode Mentor extension');

  // Command registration
  let disposable = vscode.commands.registerCommand('leetcode-mentor.createFile', async (data) => {
    try {
      const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
      if (!workspaceFolder) throw new Error('No workspace folder open');

      const fileName = `${data.problemName}.cpp`;
      const filePath = vscode.Uri.joinPath(workspaceFolder.uri, fileName);
      const content = `// LeetCode Solution for ${data.problemName}\n// Generated by LeetCode Mentor\n\n${data.code}\n`;

      await vscode.workspace.fs.writeFile(filePath, Buffer.from(content, 'utf8'));
      const document = await vscode.workspace.openTextDocument(filePath);
      await vscode.window.showTextDocument(document);

      vscode.window.showInformationMessage(`Created file: ${fileName}`);
    } catch (err) {
      vscode.window.showErrorMessage(`Failed to create file: ${err.message}`);
    }
  });

  context.subscriptions.push(disposable);

  // URI handler
  vscode.window.registerUriHandler({
    handleUri(uri) {
      if (uri.path === '/createFile') {
        try {
          const data = JSON.parse(decodeURIComponent(uri.query));
          vscode.commands.executeCommand('leetcode-mentor.createFile', data);
        } catch (err) {
          vscode.window.showErrorMessage(`Invalid URI: ${err.message}`);
        }
      }
    }
  });
}

function deactivate() {}

module.exports = { activate, deactivate };
